import pandas as pd
from datetime import datetime
import csv

import streamlit as st

from query_chatbot import QueryChatbot
from config.logger import setup_logger

st.set_page_config(
    page_title="Know Nour! By Nour Al-Serw",
    layout="wide",  
    initial_sidebar_state="expanded",
    page_icon="🤖"
)
chatbot = QueryChatbot()
logger = setup_logger(__name__)

st.title("Know Nour! By Nour Al-Serw")

if "cookie_accepted" not in st.session_state:
    st.session_state.cookie_accepted = False
if not st.session_state.cookie_accepted:
    st.markdown("""
        <div style="position: fixed; bottom: 0; left: 0; right: 0; background-color: #f0f2f6; 
        padding: 15px; z-index: 9999; border-top: 1px solid #ccc; text-align: center;">
            🍪 This app logs your questions and answers to improve the experience. Do you accept?
                Note that if you decline, you will be redirected to a 404 page.
        </div>
        <style>
        div[data-testid="stHorizontalBlock"] {
            position: fixed;
            bottom: 60px;
            left: 50%;
            transform: translateX(-50%);
            z-index: 10000;
            width: auto;
        }
        div[data-testid="stHorizontalBlock"] button {
            width: 100px !important;
        }
        </style>
    """, unsafe_allow_html=True)

    col1, col2 = st.columns(2)
    with col1:
        if st.button("Accept"):
            st.session_state.cookie_accepted = True
            st.rerun()
    with col2:
        if st.button("Decline"):
            st.markdown('<meta http-equiv="refresh" content="0; url=https://httpstat.us/404">', unsafe_allow_html=True)
            st.stop()
    st.stop()


chatbotTab, InfoTab, Contact = st.tabs(["Chat with the Bot", "About This Project", "Contact Me"])

with chatbotTab:
    
    user_input = st.text_input("Ask me anything about my experience, skills, or background!")
    
    submit_button = st.button("Submit")

    if submit_button and user_input:
        user_input_timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        with st.spinner("Generating response..."):
            response = chatbot.get_response(user_input)
            response_timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            response_time = (datetime.now() - datetime.strptime(user_input_timestamp, "%Y-%m-%d %H:%M:%S")).total_seconds()
        st.markdown(f"**Response:** {response['result']}")
        with open("logs/questions_answers.csv", mode="a", newline="", encoding="utf-8") as log_file:
            writer = csv.writer(log_file)
            if log_file.tell() == 0:  # If file is empty, write header
                writer.writerow(["Question", "Answer", "Question timestamp", "Answer timestamp", "Response time"])
            writer.writerow([user_input, response['result'], user_input_timestamp, response_timestamp, response_time])
        logger.info("Logged question and answer to CSV")
        
with InfoTab:
    st.header("About This Project")
    st.markdown("""
    This project is a personal chatbot built using LangChain, ChromaDB, and Ollama. It allows users to ask questions about my experience, skills, and background, 
                and provides responses based on the information stored in the vector database. The chatbot is designed to be a fun and interactive way for 
                anyone who wishes to learn more about me to do so in a conversational manner.
    
    **Key Features:**
    - Natural language understanding with HuggingFace embeddings
    - Fast retrieval of relevant information using ChromaDB
    - High-quality responses generated by Ollama's LLM
    
    Feel free to explore the chatbot and ask any questions you have!
    """)
    st.markdown("""
                **Note:** The chatbot's responses are based on the information available in the vector database, 
                which is populated from PDF documents. If you have any specific questions or want to see more information, please let me know!""")
    
with Contact:
    st.header("Contact Me")
    st.markdown("""
    If you'd like to get in touch with me, feel free to reach out through any of the following channels:
                
      """)
    
    contact_table = pd.DataFrame({
        "Platform": ["LinkedIn", "GitHub", "Email"],
        "Contact": ["[Nour Al-Serw](https://www.linkedin.com/in/nour-al-serw/)", "[nouralserw](https://github.com/NourSerw)", "nouralserw@gmail.com"]
    })
    df_display = contact_table.reset_index(drop=True)
    df_display.index = [''] * len(df_display)
    st.table(df_display)

