import streamlit as st
import pandas as pd

from query_chatbot import QueryChatbot

st.set_page_config(
    page_title="Know Nour! By Nour Al-Serw",
    layout="wide",  
    initial_sidebar_state="expanded"  
)

st.title("Know Nour! By Nour Al-Serw")

chatbotTab, InfoTab, Contact = st.tabs(["Chat with the Bot", "About This Project", "Contact Me"])

with chatbotTab:
    user_input = st.text_input("Ask me anything about my experience, skills, or background!")
    
    submit_button = st.button("Submit")

    if submit_button and user_input:
        with st.spinner("Generating response..."):
            chatbot = QueryChatbot()
            response = chatbot.get_response(user_input)
        st.markdown(f"**Response:** {response['result']}")

with InfoTab:
    st.header("About This Project")
    st.markdown("""
    This project is a personal chatbot built using LangChain, ChromaDB, and Ollama. It allows users to ask questions about my experience, skills, and background, 
                and provides responses based on the information stored in the vector database. The chatbot is designed to be a fun and interactive way for 
                anyone who wishes to learn more about me to do so in a conversational manner.
    
    **Key Features:**
    - Natural language understanding with HuggingFace embeddings
    - Fast retrieval of relevant information using ChromaDB
    - High-quality responses generated by Ollama's LLM
    
    Feel free to explore the chatbot and ask any questions you have!
    """)
    st.markdown("""
                **Note:** The chatbot's responses are based on the information available in the vector database, 
                which is populated from PDF documents. If you have any specific questions or want to see more information, please let me know!""")
    
with Contact:
    st.header("Contact Me")
    st.markdown("""
    If you'd like to get in touch with me, feel free to reach out through any of the following channels:
                
      """)
    
    contact_table = pd.DataFrame({
        "Platform": ["LinkedIn", "GitHub", "Email"],
        "Contact": ["[Nour Al-Serw](https://www.linkedin.com/in/nour-al-serw/)", "[nouralserw](https://github.com/NourSerw)", "nouralserw@gmail.com"]
    })
    df_display = contact_table.reset_index(drop=True)
    df_display.index = [''] * len(df_display)
    st.table(df_display)

